# Generated by Django 2.2.3 on 2019-07-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
