# Generated by Django 2.2.3 on 2019-07-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(max_length=255),
        ),
    ]
