# Generated by Django 2.2.3 on 2019-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Route', '0002_auto_20190707_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='route',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='route',
            name='date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='route',
            name='income',
        ),
        migrations.RemoveField(
            model_name='route',
            name='income_tax',
        ),
        migrations.RemoveField(
            model_name='route',
            name='petrol',
        ),
        migrations.RemoveField(
            model_name='route',
            name='pra',
        ),
        migrations.RemoveField(
            model_name='route',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='route',
            name='total_expense',
        ),
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
