# Generated by Django 2.2.3 on 2019-08-13 15:59

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonmodel',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), size=None),
        ),
    ]
